---
- name: Provisionamento do Servidor WEB com Docker
  hosts: all
  become: yes # Executa tudo como root (sudo)

  tasks:
    - name: 1. Atualizar o sistema operacional (Update e Upgrade)
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        dpkg_options: 'force-confold,force-confdef'
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: 2. Instalar dependências essenciais
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: 3. Adicionar a chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: 4. Adicionar o repositório oficial do Docker para o Debian Bookworm
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker

    - name: 5. Instalar o Docker e o Docker Compose (Plugin V2)
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: 6. Criar diretório do projeto na VM
      file:
        path: /opt/projeto-docker
        state: directory
        mode: '0755'

    - name: 7. Inserir o conteúdo do arquivo docker-compose.yml na VM
      copy:
        src: ./docker-compose.yml
        dest: /opt/projeto-docker/docker-compose.yml


    - name: 75. Inserir o arquivo de variaveis ocultas (.env) na VM
      copy:
        src: ./.env
        dest: /opt/projeto-docker/.env

    - name: 8. Executar o Docker Compose para iniciar a infraestrutura
      command: docker compose up -d
      args:
        chdir: /opt/projeto-docker
