user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

# ----------------------------------------------------
# CONFIGURAÇÃO DE CAMADA 4 (TCP) - LOAD BALANCER
# ----------------------------------------------------
stream {
    upstream backend_webserver {
        # Aponta para o container que se chamará "webserver" na porta 80
        server webserver:80;
    }

    server {
        # Escuta na porta 8080 em L4 (TCP)
        listen 8080;
        
        # Encaminha o tráfego diretamente para o upstream
        proxy_pass backend_webserver;
    }
}
